[package]
name = "my_logger"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
env_logger = { version = "0.11.3", features = ["default", "color"] }
log = "0.4.21"
